updated ftp script to latest version from hippie
added ftp dump script for usb drive support

diff --git a/ftpdump b/ftpdump
--- a/ftpdump
+++ b/ftpdump
@@ -41,6 +41,7 @@ Exit the script at any time by pressing CTRL-C.
 Options:
   -a, --app          Dump app data.
       --appdb        Dump app.db file and quit.
+      --beep         Beep when done.
   -d, --dlc          Dump DLC data.
       --debug        Print debug information.
       --debug-pfs    Print debug information while extracting a PFS image file.
@@ -72,10 +73,12 @@ debug_message() {
 
 warning_message() {
   echo -e "\r\e[93mWARNING: $1\e[39m" >&2
+  ((warnings++))
 }
 
 critical_message() {
   echo -e "\r\e[91mCRITICAL: $1\e[39m" >&2
+  ((criticals++))
 }
 
 # Parses command line arguments, creating C-like argc and argv; called with $@
@@ -100,6 +103,28 @@ build_args() {
   [[ $debug ]] && debug_message "Expanded arguments: ${argv[*]}"
 }
 
+# Beeps to signal script completion
+beep_function() {
+  # Only beep for larger tasks or when explicitly enabled
+  if [[ ($beep == true && $dump_app$dump_patch$dump_dlc) || $force_beep ]]; then
+    trap exit SIGINT
+    printf "\n(Press CTRL-C to stop beeping.)\n"
+
+    if [[ ! $beep_time ]]; then
+      beep_time=60
+    fi
+    if [[ ! $beep_interval ]]; then
+      beep_interval=3
+    fi
+    local i=0
+    while [[ $i -le $beep_time ]]; do
+      echo -en "\a"
+      sleep $beep_interval
+      ((i += beep_interval))
+    done
+  fi
+}
+
 # Stops all downloads the FTP server might still be trying to send
 # Requires the server to support the custom command KILL
 kill_downloads() {
@@ -111,11 +136,13 @@ kill_downloads() {
 # Properly stops all downloads, then exits the script
 # $1: exit code, $2: optional message
 clean_exit() {
+  local exit_code=$1
   kill $(jobs -p) 2> /dev/null
   wait
   kill_downloads
   if [[ -f "$error_file" ]]; then
     if [[ -s "$error_file" ]]; then
+      [[ $exit_code -eq 0 ]] && exit_code=1
       echo "Error log:"
       cat "$error_file"
     fi
@@ -125,11 +152,17 @@ clean_exit() {
   if [[ $2 ]]; then
     echo "$2"
   fi
-  exit $1
+  [[ $exit_code -eq 0 ]] && echo "Done."
+  [[ $warnings -gt 0 ]] && echo -e "\e[93m$warnings\e[39m warning message(s)."
+  [[ $criticals -gt 0 ]] && echo -e "\e[91m$criticals\e[39m critical message(s)."
+  beep_function
+  exit $exit_code
 }
 
 # User has pressed CTRL-C or sent SIGINT otherwise
 sigint_exit() {
+  unset beep
+  unset force_beep
   clean_exit 0 "Script aborted by user."
 }
 
@@ -161,14 +194,6 @@ check_for_errors() {
   fi
 }
 
-# Used by the main process before the script exits, as a final job error check
-check_for_errors_and_exit() {
-  wait
-  check_for_errors
-  echo "Done."
-  exit 0
-}
-
 # Called when cURL encounters an error
 # $1: optional file name
 curl_error() {
@@ -196,7 +221,7 @@ wget_error() {
     8) e="Server issued an error response" ;;
     *) e="Unknown error (see https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html" ;;
   esac
-  abort "Wget reported error $1: $e."
+  abort "Wget reported error $1: \"$e.\""
 }
 
 # Portable replacement for GNU realpath
@@ -231,7 +256,7 @@ disable_download_progress() {
 dump_file() {
   local new_file=${1##*/}
 
-  [[ $curl_verbose ]] && echo -en "\e[2K\e[36m"
+  [[ $verbose ]] && echo -en "\e[2K\e[36m"
 
   # Download partial file
   if [[ $2 ]]; then
@@ -239,13 +264,29 @@ dump_file() {
       "${1//#/%23}" | dd "$dd_options" skip="$2" count="$3" 2> /dev/null \
       > "$new_file" || curl_error "$1"
     kill_downloads
-    [[ $curl_verbose ]] && echo -en "\e[39m"
+    [[ $verbose ]] && echo -en "\e[39m"
   # Download full file
   else
-    while read -r line; do
-      [[ $line && $line != *" -> "* ]] && echo "$line"
-    done < <(wget --no-verbose $wget_options $wget_resume $wget_verbose \
-      "$1" --output-document "$new_file" 2>&1 || wget_error $?)
+    wget --no-verbose $wget_options $wget_resume $wget_verbose \
+      "$1" --output-document "$new_file" 2>&1 | \
+      while read -r line; do
+        [[ $line && $line != *" -> "* ]] && echo "$line"
+      done
+
+    # Abort script if download has failed
+    local result=${PIPESTATUS[0]}
+    if [[ $result -gt 0 ]]; then
+      # Remove file if its size is 0
+      if [[ -f "$new_file" && ! -s "$new_file" ]]; then
+        [[ $debug ]] && debug_message \
+          "Download failed - removing empty file \"$new_file\"."
+        rm "$new_file" &> /dev/null
+      fi
+
+      [[ $verbose ]] && echo -en "\e[39m"
+      wget_error $result
+    fi
+
     echo -e "\e[2K\r\e[39m$new_file"
   fi
 }
@@ -268,26 +309,34 @@ dump_dir() {
     "Dumping directory \"$line\", cutting $dir_count directories."
 
   # Download directory recursively
-  while read -r line; do
-    if [[ $line == *" ->"* ]]; then
-      file_name=${line%\"*}
-      file_size=${file_name%]*}
-      file_size=${file_size##*[}
-      file_name=${file_name##*\"}
-      if [[ $file_name != *.listing ]]; then # Ignore Wget's temporary files
-        echo -e "\e[2K\r$file_name"
-        # Update download progress
-        if [[ $download_progress_enabled ]]; then
-          ((downloaded_bytes += file_size))
-          print_download_progress
-        fi
-      fi
-    elif [[ $wget_verbose && $line != "" ]]; then
-      echo -e "\e[36m$line\e[39m"
-    fi
-  done < <(wget --cut-dirs $dir_count --no-host-directories --no-parent \
+  wget --cut-dirs $dir_count --no-host-directories --no-parent \
     --no-verbose --recursive $wget_options $wget_resume $wget_verbose \
-    --level inf "$1" 2>&1 || wget_error $?)
+    --level inf "$1" 2>&1 | \
+    while read -r line; do
+      if [[ $line == *" ->"* ]]; then
+        file_name=${line%\"*}
+        file_size=${file_name%]*}
+        file_size=${file_size##*[}
+        file_name=${file_name##*\"}
+        file_name=${file_name%.listing} # Wget's temporary files
+        if [[ $file_name ]]; then
+          echo -e "\e[2K\r$file_name"
+          # Update download progress
+          if [[ $download_progress_enabled ]]; then
+            ((downloaded_bytes += file_size))
+            print_download_progress
+          fi
+        fi
+      elif [[ $verbose && $line != "" ]]; then
+        echo -e "\e[36m$line\e[39m"
+      fi
+    done
+
+  # Abort script if download has failed
+  local result=${PIPESTATUS[0]}
+  if [[ $result -gt 0 ]]; then
+    wget_error $result
+  fi
 }
 
 # Enables SELF decryption, which the FTP server must support
@@ -418,9 +467,16 @@ extract_pkg() {
       filename_table_offset=$data_offset
     fi
 
+    if [[ $debug ]]; then
+      debug_message "$(printf "ID: %#x\n" $id)"
+      debug_message "File name offset: $filename_offset"
+      debug_message "Data offset: $data_offset"
+      debug_message "Size: $size"
+    fi
+
     # Extract entries that are files
     if [[ $id -ge 1024 ]]; then
-      # For files that have no name, create file names
+      # For files that have no name, create file name
       if [[ $id -lt 4096 ]]; then
         case $id in
           1024) filename=license.dat ;; # 0x400
@@ -441,19 +497,13 @@ extract_pkg() {
       elif [[ $filename_table_offset && $filename_offset -gt 0 ]]; then
         read_string filename "$1" $((filename_table_offset + filename_offset))
       fi
+      [[ $debug ]] && debug_message "File name: \"$filename\""
       # Extract file
       if [[ $resume || ! -e "$filename" ]]; then
         extract_pkg_file "$1" $data_offset $size "$filename"
       else
         warning_message "File already exists: \"$filename\" (skipped)."
       fi
-    fi
-
-    if [[ $debug ]]; then
-      debug_message "$(printf "ID: %#x\n" $id)"
-      debug_message "Filename offset: $filename_offset"
-      debug_message "Data offset: $data_offset"
-      debug_message "Size: $size"
     fi
 
     ((i++))
@@ -482,6 +532,7 @@ dump_and_extract_pkg() {
   [[ $debug ]] && debug_message \
     "Dumping body from $pkg_filename ($((body_offset + body_size)) bytes)."
   dump_file "$1" 0 $((body_offset + body_size))
+  [[ $debug ]] && debug_message "Extracting ..."
   extract_pkg "$pkg_filename"
 
   rm "$pkg_filename" || abort \
@@ -509,7 +560,6 @@ replace_encrypted_trophies() {
     echo "Checking trophy files for encryption ..."
 
     read magic_number < <(dd if="$trophy_file" bs=1 count=3 2> /dev/null)
-
     if [[ $magic_number == $(printf "\xdc\xa2\x4d") ]]; then
       echo "File \"${trophy_file##*/}\" is not encrypted."
     else
@@ -522,9 +572,8 @@ replace_encrypted_trophies() {
           > /dev/null
         mv TROPHY.TRP "$trophy_file" || abort
       else
-        echo
-          critical_message \
-            "Could not find unencrypted version of \"${trophy_file##*/}\"." >&2
+        critical_message \
+          "Could not find unencrypted version of \"${trophy_file##*/}\"." >&2
       fi
     fi
 
@@ -650,7 +699,7 @@ extract_pfs_dir() {
             extract_pfs_dir "$1" $dirent_inode_index "" # Extract true root dir
           else
             echo "Extracting $3$dirent_filename/"
-            mkdir --parents "$dirent_filename" || abort
+            mkdir -p "$dirent_filename" || abort
             cd "$dirent_filename" || abort
             extract_pfs_dir "$1" $dirent_inode_index "$3$dirent_filename/" # Extract next directory
             cd .. || abort
@@ -725,12 +774,20 @@ replace_encrypted_files() {
   done
 }
 
+# Checks if an FTP file exists
+ftp_file_exists() {
+  if curl --head --silent "$1" &> /dev/null; then
+    return 0
+  else
+    return 1
+  fi
+}
+
 # Main script: #################################################################
 
 LC_ALL=C
 main_pid=$BASHPID
 decrypt=1
-error_file=$(mktemp 2> /dev/null) # Used by the main process to spot failed jobs
 
 trap sigint_exit SIGINT # To catch CTRL-C
 
@@ -744,13 +801,14 @@ for ((i = 0; i < argc; i++)); do
       --) no_more_args=1 ;;
       -a|-g|--app|--game|--app-only) dump_app=1 ;;
       --appdb) dump_appdb=1 ;;
+      --beep) force_beep=1 ;;
       -d|--ac|--dlc|--dlc-only) dump_dlc=1 ;;
       --dump)
         if [[ $((++i)) -lt argc ]]; then
           dump_path=${argv[i]}
         else
           echo "Missing argument for option --dump." >&2
-          clean_exit 1
+          exit 1
         fi
         ;;
       --debug) debug=1 ;;
@@ -763,11 +821,11 @@ for ((i = 0; i < argc; i++)); do
           else
             echo "First non-option argument needs to follow --extract-pfs." >&2
             print_usage >&2
-            clean_exit 1
+            exit 1
           fi
         else
           echo "Missing argument for option --extract-pfs." >&2
-          clean_exit 1
+          exit 1
         fi
         ;;
       --extract-pkg)
@@ -778,16 +836,16 @@ for ((i = 0; i < argc; i++)); do
           else
             echo "First non-option argument needs to follow --extract-pkg." >&2
             print_usage >&2
-            clean_exit 1
+            exit 1
           fi
         else
           echo "Missing argument for option --extract-pkg." >&2
-          clean_exit 1
+          exit 1
         fi
         ;;
       -h|--help)
         print_usage
-        clean_exit 0
+        exit 0
         ;;
       -k|--keystone) dump_keystone=1 ;;
       --keep-trying)
@@ -805,28 +863,49 @@ for ((i = 0; i < argc; i++)); do
       --shutdown) shutdown=1 ;;
       --use-pfs) pfs_extraction_enabled=1 ;;
       -v|--verbose)
+        verbose=1
         curl_verbose=-v
         wget_verbose=-S
         ;;
       -*)
         echo "Unknown option: ${argv[i]}" >&2
         print_usage >&2
-        clean_exit 1
+        exit 1
         ;;
       *) non_options[noptc++]=${argv[i]} ;;
     esac
   fi
 done
 
+# Check Bash version
+bash_version=$(bash --version)
+bash_version=${bash_version#*bash, version }
+full_bash_version=${bash_version%% (*}
+bash_version=${bash_version:0:1}
+if [[ $bash_version == [0-9] ]]; then
+  if [[ $bash_version -ge 5 ]]; then
+    [[ $debug ]] && debug_message "Bash version \"$full_bash_version\" detected."
+  else
+    warning_message "Your Bash version \"$full_bash_version\" is heavily outdated. The script might not run properly."
+  fi
+else
+  warning_message "Could not check the Bash version. Please report this if you encounter any script errors."
+fi
+
 # Set dd options
-dd --version | grep GNU > /dev/null
+dd --version 2> /dev/null | grep GNU > /dev/null
 if [[ $? == 0 ]]; then
   [[ $debug ]] && debug_message "GNU dd detected - using GNU-specific dd options."
   dd_options="iflag=skip_bytes,count_bytes" # For GNU dd; much faster
 else
-  [[ $debug ]] && debug_message \
-    "Non-GNU dd detected - using regular dd options (slow!)."
-  dd_options="ibs=1"
+  gdd --version 2> /dev/null | grep GNU > /dev/null
+  if [[ $? == 0 ]]; then
+    [[ $debug ]] && debug_message "Homebrew GNU dd detected - using GNU-specific dd options."
+    dd_options="iflag=skip_bytes,count_bytes" # For GNU dd; much faster
+  else
+    [[ $debug ]] && debug_message "Non-GNU dd detected - using regular dd options (slow!)."
+    dd_options="ibs=1"
+  fi
 fi
 
 # Set output directory
@@ -838,6 +917,10 @@ else
   [[ $debug ]] && debug_message "Using current directory as output directory."
 fi
 
+# Temporary file used by the main process to spot failed jobs
+# From here on out, only exit with function clean_exit (which deletes the file)
+error_file=$(mktemp 2> /dev/null)
+
 # PFS image file extraction (option --extract-pfs)
 if [[ $pfs_extraction_mode ]]; then
   pfs_file=$(realpath "${non_options[0]}")
@@ -845,9 +928,9 @@ if [[ $pfs_extraction_mode ]]; then
     echo "File does not exist: \"$pfs_file\"." >&2
     clean_exit 1
   fi
-  mkdir --parents "$output_dir" && cd "$output_dir" || abort
+  mkdir -p "$output_dir" && cd "$output_dir" || abort
   extract_pfs_image "$pfs_file"
-  exit 0
+  clean_exit 0
 fi
 
 # PKG file extraction (option --extract-pkg)
@@ -857,9 +940,9 @@ if [[ $pkg_extraction_mode ]]; then
     echo "File does not exist: \"$pkg_file\"." >&2
     clean_exit 1
   fi
-  mkdir --parents "$output_dir" && cd "$output_dir" || abort
+  mkdir -p "$output_dir" && cd "$output_dir" || abort
   extract_pkg "$pkg_file"
-  exit 0
+  clean_exit 0
 fi
 
 # Dump everything by default
@@ -952,20 +1035,20 @@ elif [[ ! $goldhen_2 ]]; then
 fi
 
 # Create output directory
-mkdir --parents "$output_dir" && cd "$output_dir" || abort
+mkdir -p "$output_dir" && cd "$output_dir" || abort
 
 # Single-file dumps  -----------------------------------------------------------
 
 # Database
 if [[ $dump_appdb ]]; then
   dump_file "$root/system_data/priv/mms/app.db"
-  check_for_errors_and_exit
+  clean_exit 0
 fi
 
 # sflash0
 if [[ $dump_sflash ]]; then
   dump_file "$root/dev/sflash0"
-  check_for_errors_and_exit
+  clean_exit 0
 fi
 
 # Enable decryption, which might be needed from now on
@@ -985,7 +1068,7 @@ if [[ $dump_path ]]; then
     [[ $debug ]] && debug_message "Treating as directory: \"$dump_path\""
     dump_dir "$root$dump_path"
   fi
-  check_for_errors_and_exit
+  clean_exit 0
 fi
 
 #-------------------------------------------------------------------------------
@@ -996,7 +1079,7 @@ title_id=$(curl $curl_options --silent "$root/mnt/sandbox/" \
 title_id=${title_id##* }
 title_id=${title_id%_*}
 if [[ $title_id != CUSA[0-9][0-9][0-9][0-9][0-9] ]]; then
-  echo "Could not retreive Title ID. Is the game started?" >&2
+  echo "Could not retrieve Title ID. Is the game started?" >&2
   clean_exit 1
 fi
 
@@ -1005,7 +1088,7 @@ fi
 if [[ $dump_keystone ]]; then
   cd "$output_dir" || abort
   echo "Dumping $title_id keystone:"
-  mkdir --parents "$title_id-keystone" && cd "$title_id-keystone" || abort
+  mkdir -p "$title_id-keystone" && cd "$title_id-keystone" || abort
 
   dump_file "$root/mnt/sandbox/pfsmnt/$title_id-app0/sce_sys/keystone"
 
@@ -1019,7 +1102,7 @@ if [[ $dump_app ]]; then
 
   cd "$output_dir" || abort
   echo "Dumping $title_id app data ($((download_size / 1000000)) MB):"
-  mkdir --parents "$title_id-app" && cd "$title_id-app" || abort
+  mkdir -p "$title_id-app" && cd "$title_id-app" || abort
 
   if [[ $pfs_extraction_enabled ]]; then
     dump_and_extract_pfs_image \
@@ -1031,12 +1114,26 @@ if [[ $dump_app ]]; then
     disable_download_progress
   fi
 
-  mkdir --parents sce_sys && cd sce_sys || abort
-  dump_and_extract_pkg "$root/user/app/$title_id/app.pkg"
-  echo "Replacing npbind.dat and nptitle.dat ..."
-  dump_file "$root/System_data/priv/appmeta/$title_id/npbind.dat"
-  dump_file "$root/System_data/priv/appmeta/$title_id/nptitle.dat"
-  replace_encrypted_trophies
+  mkdir -p sce_sys && cd sce_sys || abort
+  if ftp_file_exists "$root/user/app/$title_id/app.pkg"; then
+    dump_and_extract_pkg "$root/user/app/$title_id/app.pkg"
+  elif ftp_file_exists "$root/mnt/ext0/user/app/$title_id/app.pkg"; then
+    dump_and_extract_pkg "$root/mnt/ext0/user/app/$title_id/app.pkg"
+  else
+    abort "Could not find FTP file \"app.pkg\"."
+  fi
+
+  if [[ -f param.sfo ]] && grep -ao REMASTER_TYPE param.sfo &> /dev/null; then
+    warning_message \
+      "App is of type \"remaster\" - editing the param.sfo might be necessary."
+  fi
+
+  if [[ -f npbind.dat ]]; then
+    echo "Replacing npbind.dat and nptitle.dat ..."
+    dump_file "$root/System_data/priv/appmeta/$title_id/npbind.dat"
+    dump_file "$root/System_data/priv/appmeta/$title_id/nptitle.dat"
+    replace_encrypted_trophies
+  fi
 fi
 
 # Dump patch data --------------------------------------------------------------
@@ -1051,7 +1148,7 @@ if [[ $dump_patch ]]; then
 
     cd "$output_dir" || abort
     echo "Dumping $title_id patch data ($((download_size / 1000000)) MB):"
-    mkdir --parents "$title_id-patch" && cd "$title_id-patch" || abort
+    mkdir -p "$title_id-patch" && cd "$title_id-patch" || abort
 
     if [[ $pfs_extraction_enabled ]]; then
       dump_and_extract_pfs_image \
@@ -1063,12 +1160,21 @@ if [[ $dump_patch ]]; then
       disable_download_progress
     fi
 
-    mkdir --parents sce_sys && cd sce_sys || abort
-    dump_and_extract_pkg "$root/user/patch/$title_id/patch.pkg"
-    echo "Replacing npbind.dat and nptitle.dat ..."
-    dump_file "$root/System_data/priv/appmeta/$title_id/npbind.dat"
-    dump_file "$root/System_data/priv/appmeta/$title_id/nptitle.dat"
-    replace_encrypted_trophies
+    mkdir -p sce_sys && cd sce_sys || abort
+    if ftp_file_exists "$root/user/patch/$title_id/patch.pkg"; then
+      dump_and_extract_pkg "$root/user/patch/$title_id/patch.pkg"
+    elif ftp_file_exists "$root/mnt/ext0/user/patch/$title_id/patch.pkg"; then
+      dump_and_extract_pkg "$root/mnt/ext0/user/patch/$title_id/patch.pkg"
+    else
+      abort "Could not find FTP file \"patch.pkg\"."
+    fi
+
+    if [[ -f npbind.dat ]]; then
+      echo "Replacing npbind.dat and nptitle.dat ..."
+      dump_file "$root/System_data/priv/appmeta/$title_id/npbind.dat"
+      dump_file "$root/System_data/priv/appmeta/$title_id/nptitle.dat"
+      replace_encrypted_trophies
+    fi
   else
     echo "No patch data found."
   fi
@@ -1089,7 +1195,7 @@ if [[ $dump_dlc ]]; then
   if [[ $dlc_dirs ]]; then
     cd "$output_dir" || abort
     echo "Dumping $title_id DLC data:"
-    mkdir --parents "$title_id-dlc" && cd "$title_id-dlc" || abort
+    mkdir -p "$title_id-dlc" && cd "$title_id-dlc" || abort
     for dir in $dlc_dirs; do
       mkdir "$dir" && cd "$dir" || abort
       dump_dir "$root/mnt/sandbox/pfsmnt/$dir/"
@@ -1102,21 +1208,4 @@ fi
 
 #-------------------------------------------------------------------------------
 
-# Beep when done
-if [[ $beep == true ]]; then
-  echo "Press CTRL-C to stop beeping."
-  if [[ ! $beep_time ]]; then
-    beep_time=60
-  fi
-  if [[ ! $beep_interval ]]; then
-    beep_interval=3
-  fi
-  i=0
-  while [[ $i -le $beep_time ]]; do
-    echo -en "\a"
-    sleep $beep_interval
-    ((i += beep_interval))
-  done
-fi
-
-check_for_errors_and_exit
+clean_exit 0
